[package]
name = "beacon-api-sidecar-fetcher"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
reth-node-ethereum.workspace = true
serde.workspace = true
serde_json.workspace = true 


reqwest = "0.12.3"
pin-project.workspace = true
clap.workspace = true
tracing.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["time"] }
eyre.workspace = true
thiserror.workspace = true